#port
server.port=9092

#hibernate configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

#datasource config con valores por defecto
spring.datasource.url=jdbc:mysql://${DB_IP:localhost}:${DB_PORT:3306}/${DB_NAME:microadopter}
#sin valores por defecto
#spring.datasource.url=jdbc:mysql://${DB_IP}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER:root}
#spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD:Pa55w.rd1!}
#spring.datasource.password=${DB_PASSWORD}

# eureka config
eureka.client.service-url.defaultZone=http://${EUREKA_IP:localhost}:${EUREKA_PORT:9999}/eureka
#eureka.client.service-url.defaultZone=http://${EUREKA_IP}:${EUREKA_PORT}/eureka